# Fiets of OV — common dev commands. Run `make` (or `make help`) to list them.
# Targets use the project venv directly, so no `source .venv/bin/activate` needed.
# App config (DB/Redis/OTP URLs, JWT secret, …) is read from .env — see .env.example.

VENV := .venv/bin
PORT ?= 8000

.DEFAULT_GOAL := help

.PHONY: help install run worker migrate revision test lint ci otp up up-otp down

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

install: ## Install the app + dev dependencies into the venv
	$(VENV)/pip install -e ".[dev]"

run: ## Run the API with autoreload (http://localhost:$(PORT))
	$(VENV)/uvicorn app.main:app --reload --port $(PORT)

worker: ## Run the ARQ background worker (rain notifications)
	$(VENV)/arq app.workers.main.WorkerSettings

migrate: ## Apply database migrations (alembic upgrade head)
	$(VENV)/alembic upgrade head

revision: ## New autogenerated migration: make revision m="message"
	$(VENV)/alembic revision --autogenerate -m "$(m)"

test: ## Run the test suite
	$(VENV)/pytest

lint: ## Lint and auto-format
	$(VENV)/ruff check . && $(VENV)/ruff format .

ci: ## Run the exact CI checks locally (lint + format-check + tests) before pushing
	$(VENV)/ruff check .
	$(VENV)/ruff format --check .
	$(VENV)/pytest

otp: ## Run the self-hosted OpenTripPlanner (needs otp/data inputs — see otp/README.md)
	bash otp/scripts/run_otp.sh

up: ## Full stack in Docker (app + Postgres + Redis)
	docker compose up

up-otp: ## Full stack + self-hosted OpenTripPlanner overlay
	docker compose -f docker-compose.yml -f docker-compose.otp.yml up

down: ## Stop and remove the Docker stack
	docker compose down
