"""create stops table

Revision ID: 0001_create_stops
Revises:
Create Date: 2026-05-30

First migration: the GVB `stops` table (Phase 4). Hand-written rather than autogenerated so
it needs no live DB to author and its constraint/index names match the model's naming
convention (pk_stops, ix_stops_lat_lon). The composite (lat, lon) index serves the
bounding-box prefilter of the nearby-stop search.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_create_stops"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "stops",
        sa.Column("stop_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("location_type", sa.Integer(), server_default="0", nullable=False),
        sa.Column("parent_station", sa.String(), nullable=True),
        sa.Column("platform_code", sa.String(), nullable=True),
        sa.Column("zone_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("stop_id", name="pk_stops"),
    )
    op.create_index("ix_stops_lat_lon", "stops", ["lat", "lon"])


def downgrade() -> None:
    op.drop_index("ix_stops_lat_lon", table_name="stops")
    op.drop_table("stops")
